### ISSUE TITLE
Consider adding Ulid wrapper.

### ISSUE THREAD

**Issue by bboyle1234** [devlooped/StructId#18]
Best id type I know so far :) 

https://github.com/Cysharp/Ulid

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by bboyle1234** [comment]
I can't tell from the readme if we're able to create our own custom templates for this yet.

**Comment by kzu** [comment]
Progress on templates: https://github.com/devlooped/StructId/pull/21

**Comment by bboyle1234** [comment]
Yeah it's amazing. Best ever.

**Comment by kzu** [comment]
Next stop: Ulid!

https://github.com/devlooped/StructId#customization-via-templates

**Comment by bboyle1234** [comment]
:)

**Comment by kzu** [comment]
Initial unofficial support as a sample: https://github.com/devlooped/StructId/pull/39

**Comment by kzu** [comment]
That's a wrap! 

https://github.com/devlooped/StructId?tab=readme-ov-file#ulid
