### ISSUE TITLE
Not able to define an string ID

### ISSUE THREAD

**Issue by hoangductranit** [devlooped/StructId#62]
I tried defining an ID for my entity, where the ID is stored in the database as CHAR(50), using the following code:

```c#
public readonly partial record struct CRM_BS_ROLE_ID(string Value) : IStructId<string>;
``` 
However, it’s throwing an error
The type 'string' must be a non-nullable value type in order to use it as parameter 'TValue' in the generic type or method 'IStructId<TValue>'

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
You don't need a T for string. Just implement `IStructId` with no type.
